homepage: "https://docs.rs/rav1e/latest/rav1e/"
main_repo: 'https://github.com/barrbrain/rav1e/'
primary_contact: "b@rr-dav.id.au"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
